apiVersion: v1
kind: Namespace
metadata:
  name: redis-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  namespace: redis-system
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy: { }
  template:
    metadata:
      labels:
        app: redis
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: redis
          image: redis:6.2.7
          resources:
            limits:
              cpu: "1000m" # Up to 1 full core
            requests:
              cpu: "1000m" # Use 1 full core
          imagePullPolicy: Always
          ports:
            - name: postgres
              containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-system
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis