basePath: /
definitions:
  responses.Health:
    properties:
      buildVersion:
        example: localhost
        type: string
    type: object
  responses.SuccessHealth:
    properties:
      health:
        $ref: '#/definitions/responses.Health'
      status:
        example: OK
        type: string
    type: object
info:
  contact: {}
  description: Devices Simulator documentation API.
  title: Swagger MYC-DEVICE-SIMULATOR API
  version: "1.0"
paths:
  /api/health:
    get:
      consumes:
      - application/json
      description: Get status service to be alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SuccessHealth'
      summary: Health check EndPoint
      tags:
      - Health
swagger: "2.0"
